baseURL = 'https://fracz.github.io/dydaktyka/mwo/meetings-fullstack'
languageCode = 'pl-pl'
title = 'MWO - Meeting Fullstack'
theme = 'relearn'
themesDir = '../../themes'
publishDir = '../../public/mwo/meetings-fullstack'
