baseURL = 'https://fracz.github.io/dydaktyka/mwo/meetings-fullstack'
languageCode = 'pl-pl'
title = 'MWO - Meeting Fullstack'
theme = 'relearn'
themesDir = '../../themes'
publishDir = '../../public/mwo/meetings-fullstack'

defaultContentLanguage = "pl"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
canonifyurls = true

[params]
editURL = "https://github.com/fracz/dydaktyka/edit/main/mwo/meetings-fullstack/content/"
author = "Wojciech Frącz"
showVisitedLinks = false
disableSearch = true
disableBreadcrumb = true
disableAssetsBusting = false
disableInlineCopyToClipBoard = false
disableShortcutsTitle = false
disableLanguageSwitchingButton = true
ordersectionsby = "weight"
themeVariant = "green" # choose theme variant "green", "gold" , "gray", "blue" (default)

[outputs]
home = [ "HTML" ]
